question_data = [
    {"type": "multiple",
     "difficulty":"hard",
     "category": "History",
     "question": "In which year did the Tokyo Subway Sarin Attack occur?",
     "correct_answer": "1995",
     "incorrect_answers": ["2001", "2011", "1991"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "Entertainment: Video Games",
     "question": "Which of the following is a class in the game &quot;Hearthstone&quot;?",
     "correct_answer": "Priest",
     "incorrect_answers": ["Sage", "Cleric", "Monk"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Science &amp; Nature",
     "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "hard",
     "category": "Entertainment: Video Games",
     "question": "How many playable characters are there in Super Smash Bros. for Nintendo 3DS and Wii U?",
     "correct_answer": "58", "incorrect_answers": ["48", "51", "55"]},
    {"type": "multiple", "difficulty": "medium", "category": "Geography",
     "question": "What city  has the busiest airport in the world?",
     "correct_answer": "Atlanta, Georgia USA",
     "incorrect_answers": ["London, England", "Chicago,Illinois ISA",
                           "Tokyo,Japan"]},
    {"type": "multiple", "difficulty": "easy",
     "category": "General Knowledge",
     "question": "What is the largest organ of the human body?",
     "correct_answer": "Skin",
     "incorrect_answers": ["Heart", "large Intestine", "Liver"]},
    {"type": "boolean", "difficulty": "easy",
     "category": "Science: Computers", "question": "A Mac is not a PC",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "Super Mario Bros. was released in 1990.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Science &amp; Nature",
     "question": "The medical condition osteoporosis affects which part of the body?",
     "correct_answer": "Bones",
     "incorrect_answers": ["Skin", "Brain", "Heart"]},
    {"type": "multiple", "difficulty": "medium",
     "category": "Entertainment: Video Games",
     "question": "Which of the following characters were considered for inclusion in Super Smash Bros. Melee?",
     "correct_answer": "Lucas",
     "incorrect_answers": ["Mega Man", "Meta Knight", "Diddy Kong"]}
]
